server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  profiles:
    active: test
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  messages:
    encoding: UTF-8
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sks.precheck.dashboard.dto
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.sks.precheck: DEBUG
    org.mybatis: DEBUG
    org.springframework.web: INFO
