spring:
  datasource:
    url: jdbc:Altibase://192.168.x.x:20300/precheck
    username: precheck
    password: (운영 비밀번호)
    driver-class-name: Altibase.jdbc.driver.AltibaseDriver
    hikari:
      maximum-pool-size: 10
      pool-name: PreCheckPool-Prod

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
